language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
env:
- POLIB_VERSION=1.0.0
- POLIB_VERSION=
matrix:
  allow_failures:
  - python: pypy3
    env: POLIB_VERSION=1.0.0
  - python: pypy3
    env: POLIB_VERSION=
install:
- pip install polib${POLIB_VERSION:+==$POLIB_VERSION}
- pip install pyflakes
- pip install rply
script:
- python tests/run-tests -v
- ./private/run-pyflakes

# vim:ts=2 sts=2 sw=2 et
