language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
env:
- POLIB_VERSION=1.0.0
- POLIB_VERSION=
- PYLINT=y
matrix:
  exclude:
  - python: "3.2"
    env: PYLINT=y
  - python: "3.7-dev"
    env: PYLINT=y
  - python: pypy3
    env: PYLINT=y
install:
- \[ -z "$PYLINT" ] || pip install --upgrade pip
- pip install polib${POLIB_VERSION:+==$POLIB_VERSION}
- pip install rply
- \[ -n "$PYLINT" ] || pip install docutils
- \[ -n "$PYLINT" ] || pip install pydiatra
- \[ -n "$PYLINT" ] || pip install pyflakes
- \[ -z "$PYLINT" ] || pip install pylint
- \[ -z "$PYLINT" ] || pip install pytz  # for private/update-timezones
- \[ -z "$PYLINT" ] || pip install --verbose cython
- \[ -z "$PYLINT" ] || pip install --verbose python-afl
script:
- \[ -n "$PYLINT" ] || tests/run-tests -v
- \[ -n "$PYLINT" ] || make -C doc/
- \[ -n "$PYLINT" ] || private/check-rst
- \[ -n "$PYLINT" ] || private/run-pydiatra
- \[ -n "$PYLINT" ] || private/run-pyflakes
- \[ -z "$PYLINT" ] || private/run-pylint

# vim:ts=2 sts=2 sw=2 et
