language: python
python:
- "3.2"
- "3.3"
- "3.4"
env:
- POLIB_VERSION=1.0.0
- POLIB_VERSION=
install:
- pip install polib${POLIB_VERSION:+==$POLIB_VERSION}
script:
- python tests/run-tests -v

# vim:ts=2 sts=2 sw=2 et
