dist: trusty
language: python
before_install:
- polib="polib==$POLIB"
- polib="${polib%==}"
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install $polib
- python3 -m pip install rply
- python3 -m pip install docutils
- python3 -m pip install pydiatra $pyflakes
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- tests/run-tests -v
- make -C doc/
- private/check-rst
- python3 -m pydiatra .
- python3 -m pyflakes .
- make install PREFIX=~/.local
- cd /
- i18nspector --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 i18nspector | grep -A 10 -w I18NSPECTOR
jobs:
  include:
  - python: "3.3"
    env: POLIB=1.0.0
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
  - python: pypy3.5-5.8.0
  - &pylint
    env: PYLINT=y
    python: "3.4"
    cache: pip
    install:
    - python3 -m pip install polib
    - python3 -m pip install rply
    - python3 -m pip install pylint
    - python3 -m pip install pytz  # for private/update-timezones
    - python3 -m pip install cython
    - python3 -m pip install python-afl
    script:
    - private/run-pylint
  - <<: *pylint
    python: "3.5"
  - <<: *pylint
    python: "3.6"
  - <<: *pylint
    python: "3.7"
    dist: xenial

# vim:ts=2 sts=2 sw=2 et
