dist: trusty
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3.5-5.8.0
env:
- POLIB_VERSION=1.0.0
- POLIB_VERSION=
install:
- pip install polib${POLIB_VERSION:+==$POLIB_VERSION}
- pip install rply
- pip install docutils
- pip install pydiatra pyflakes
script:
- tests/run-tests -v
- make -C doc/
- private/check-rst
- python3 -m pydiatra .
- python3 -m pyflakes .
- make install PREFIX=~/.local
- cd /
- i18nspector --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 i18nspector | grep -A 10 -w I18NSPECTOR
matrix:
  include:
  - &pylint
    env: PYLINT=y
    python: "3.3"
    cache: pip
    install:
    - pip install polib
    - pip install rply
    - pip install pylint
    - pip install pytz  # for private/update-timezones
    - pip install cython
    - pip install python-afl
    script:
    - private/run-pylint
  - <<: *pylint
    python: "3.4"
  - <<: *pylint
    python: "3.5"
  - <<: *pylint
    python: "3.6"

# vim:ts=2 sts=2 sw=2 et
