language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
- pypy3
env:
- POLIB_VERSION=1.0.0
- POLIB_VERSION=
matrix:
  allow_failures:
  - python: pypy3
    env: POLIB_VERSION=1.0.0
  - python: pypy3
    env: POLIB_VERSION=
install:
- pip install polib${POLIB_VERSION:+==$POLIB_VERSION}
- pip install pyflakes
- pip install rply
- pip install docutils
script:
- python tests/run-tests -v
- ./private/run-pyflakes
- make -C doc/
- rm -f doc/*.1
- grep -r -l ft=rst doc/ | xargs -t -n1 -I{} rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
