#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2012, 2013 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

'''
checking tool for gettext POT, PO and MO files
'''

import os
import sys

# ----------------------------------------

def require_python(*version):
    if sys.version_info < version:
        try:
            import argparse
            ap = argparse.ArgumentParser()
            prog = ap.prog
        except ImportError:
            import optparse
            ap = optparse.OptionParser()
            prog = ap.get_prog_name()
        message = '{prog}: error: Python >= {ver} is required\n'.format(
            prog=prog,
            ver='.'.join(map(str, version))
        )
        ap.exit(1, message)

require_python(3, 2)

# ----------------------------------------

basedir_fallback = None
basedir = os.environ.get('I18NSPECTOR_BASEDIR', basedir_fallback)
if basedir is None:
    basedir = os.path.dirname(
        os.path.realpath(__file__)
    )
basedir = os.path.join(basedir, '')
os.stat(basedir)
sys.path[:0] = [basedir]

from lib import cli

cli.__doc__ = __doc__.strip()
cli.main(basedir)

# vim:ts=4 sw=4 et
