#!/bin/sh
if [ $# -ge 2 ]
then
    printf '%s [revision]\n' "$0" >&2
    exit 1
fi
if ! [ -d .hg ]
then
    printf '%s requires hg checkout\n' "$0" >&2
    exit 1
fi
set -e
pwd="$PWD"
revision="${1:-tip}"
name=$(hg cat -r "$revision" doc/changelog | head -n1 | cut -d ' ' -f 1)
date=$(hg log -r "$revision" --template='{date|isodate}' | head -c 10 | tr -d -)
version=$(hg cat -r "$revision" doc/changelog | head -n1 | cut -d ' ' -f2 | tr -d '()')
released=$(hg cat -r "$revision" doc/changelog | head -n1 | grep -v -w UNRELEASED || true)
[ -n "$released" ] || version="${version}rc${date}"
printf 'Revision: %s\nVersion: %s\n' "$revision" "$version" >&2
set -x
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS='--owner root --group root --mode a+rX --format ustar'
export GZIP='-9 -n'
mkdir -p "$sourceroot/$name-$version"
hg archive -r "$revision" "$sourceroot/$name-$version"
cd "$sourceroot"/*
make -C doc/
find -name '__pycache__' -exec rm -rf {} +
rm -rf .hg*
rm -rf .travis*
rm -rf doc/rtd/
rm -f private/build-source-tarball
cd ..
tar -czf "$pwd/$name-$version.tar.gz" */
rm -rf "$sourceroot"

# vim:ts=4 sts=4 sw=4 et
