#!/usr/bin/python3

# Copyright © 2012, 2013 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os
import sys

basedir = os.path.join(
    os.path.dirname(__file__),
    os.pardir,
)
sys.path[:0] = [basedir]

from lib import tags
from tests import blackbox_tests

def main():
    coverage = blackbox_tests.get_coverage()
    path = os.path.join(
        os.path.dirname(blackbox_tests.__file__),
        'coverage.txt'
    )
    sys.stdout = open(path + '.tmp', 'wt', encoding='ASCII')
    print('Generated automatically by private/update-tag-coverage. '
        'Do not edit.\n')
    for tag in tags.iter_tags():
        check = 'X' if tag.name in coverage else ' '
        print('[{check}] {tag}'.format(check=check, tag=tag.name))
    sys.stdout.close()
    os.rename(path + '.tmp', path)
    rc = 0
    for tag in sorted(set(coverage) - set(t.name for t in tags.iter_tags())):
        print('update-coverage: error: uknown tag {tag}'.format(tag=tag), file=sys.stderr)
        rc = 1
    sys.exit(rc)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
