#!/usr/bin/python3

# Copyright © 2012 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os
import shutil
import tempfile
import subprocess as ipc

xgettexts = {'xgettext', 'pygettext'}

def main():
    os.environ['LC_ALL'] = 'C'
    tmpdir = tempfile.mkdtemp(prefix='gettext-inspector.private.')
    xgettext_versions = {
        ipc.check_output([xgettext, '--version']).splitlines()[0].decode('ASCII', 'replace')
        for xgettext in xgettexts
    }
    try:
        path = os.path.join(tmpdir, 'dummy.c')
        with open(path, 'wt', encoding='ASCII') as file:
            file.write('ngettext("1", "2");')
        pos = {
            ipc.check_output([xgettext, '-o', '-', path])
            for xgettext in xgettexts
        }
    finally:
        shutil.rmtree(tmpdir)
    headers = set()
    for po in pos:
        po = po.decode('ASCII').splitlines()
        for line in po:
            if line.startswith('"'):
                header = line[1:].split(':', 1)[0]
                headers.add(header)
    basedir = os.path.join(
        os.path.dirname(__file__),
        os.pardir,
    )
    path = os.path.join(basedir, 'data', 'po-header-fields')
    with open(path, 'wt', encoding='ASCII') as file:
        print('''\
# This file has been generated automatically by
# private/update-po-header-fields. Do not edit.
#
# The following string extraction tools have been used:\
''', file=file)
        for xgettext_version in sorted(xgettext_versions):
            print('# * ' + xgettext_version, file=file)
        print(file=file)
        for header in sorted(headers):
            print(header, file=file)

if __name__ == '__main__':
    main()

# vim:ts=4 sw=4 et
