#!/usr/bin/python3

# Copyright © 2012-2016 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import datetime
import functools
import os
import subprocess as ipc
import sys
import json

class Panic(ValueError):
    pass

@functools.lru_cache()
def get_iso_codes_version():
    version = ipc.check_output(['pkg-config', 'iso-codes', '--modversion'])
    version = version.decode('ASCII').strip()
    return version

@functools.lru_cache()
def get_iso_codes_dir():
    prefix = ipc.check_output(['pkg-config', 'iso-codes', '--variable=prefix'])
    prefix = prefix.decode('ASCII').strip()
    return '{prefix}/share/iso-codes/json'.format(prefix=prefix)

def main():
    basedir = os.path.join(
        os.path.dirname(__file__),
        os.pardir,
    )
    path = os.path.join(basedir, 'data', 'iso-codes')
    sys.stdout = open(path + '.tmp', 'wt', encoding='UTF-8')
    print('''\
# This file has been generated automatically by private/update-iso-codes.
# Do not edit.
# iso-codes version: {version}
# Last update: {today}
'''.format(version=get_iso_codes_version(), today=datetime.date.today()))
    generate_iso_639()
    generate_iso_3166()
    sys.stdout.close()
    os.rename(path + '.tmp', path)

def load_json(path):
    with open(path, 'rt', encoding='UTF-8') as file:
        return json.load(file)

def check_length(s, n):
    if s is None:
        return
    if len(s) != n:
        raise Panic('len({!r}) != {n}'.format(s, n))

def generate_iso_639():
    # =======================
    # ISO 639: language codes
    # =======================
    data = load_json(get_iso_codes_dir() + '/iso_639-3.json')
    codes = {}
    refnames = set()
    for item in data['639-3']:
        code2 = item.get('alpha_2')
        if code2 == 'sh':
            # “sh” is deprecated
            code2 = None
        check_length(code2, 2)
        code3t = item['alpha_3']
        code3b = item.get('bibliographic')
        code = code2 or code3t
        for c in code3t, code3b:
            check_length(c, 3)
            if c is None:
                continue
            if c == code:
                codes[c] = ''
            else:
                codes[c] = code
        scope = item['scope']
        if scope == 'S':
            # Not a real language, ignore.
            continue
        elif scope in {'M', 'I'}:
            pass
        else:
            raise Panic('unknown scope: {!r}'.format(scope))
        name = item['name']
        if name in refnames:
            raise Panic('duplicate reference name: {!r}'.format(name))
        refnames.add(name)
    print('[language-codes]')
    for alias, code in sorted(codes.items()):
        print('{} = {}'.format(alias, code).rstrip())
    print()

def generate_iso_3166():
    # =========================
    # ISO 3166: territory codes
    # =========================
    iso_3166 = set()
    data = load_json(get_iso_codes_dir() + '/iso_3166-1.json')
    for item in data['3166-1']:
        cc = item['alpha_2']
        iso_3166.add(cc)
    print('[territory-codes]')
    for cc in sorted(iso_3166):
        print('{} ='.format(cc))
    print()
    print('# vi''m:ft=dosini')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
