#!/usr/bin/python3

# Copyright © 2012 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os
import re
import sys
import urllib.request

basedir = os.path.join(
    os.path.dirname(__file__),
    os.pardir,
)
sys.path[:0] = [basedir]

from lib import ling

def strip_plural_forms(s):
    # Remove superfluous parentheses around the plural formula:
    return re.sub(r'\bplural=\((.*?)\);$', r'plural=\1;', s)

def main():
    regexp = re.compile(r'\s+{\s*"([a-zA-Z_]+)".*"(nplurals.*?)"')
    datadir = os.path.join(basedir, 'data')
    linginfo = ling.LingInfo(datadir)
    # ---------
    url = 'http://git.savannah.gnu.org/cgit/gettext.git/plain/gettext-tools/src/plural-table.c'
    okay = set()
    with urllib.request.urlopen(url) as file:
        for line in file:
            line = line.decode('ASCII').rstrip()
            match = regexp.match(line)
            if match is None:
                continue
            language, gettext_plural_forms = match.groups()
            gettext_plural_forms = strip_plural_forms(gettext_plural_forms)
            try:
                our_plural_forms = linginfo.get_plural_forms(language)
            except LookupError:
                our_plural_forms = None
            if our_plural_forms != gettext_plural_forms:
                print('[{}]'.format(language))
                if our_plural_forms != None:
                    print('# plural-forms = ' + our_plural_forms)
                print('plural-forms = ' + gettext_plural_forms)
                print()
            else:
                okay.add(language)
    n_okay = len(okay)
    print('# No plural-forms changes required for {} languages'.format(n_okay))
    print()
    # ---------
    url = 'http://git.savannah.gnu.org/cgit/gettext.git/plain/gettext-tools/src/msginit.c'
    okay = set() 
    with urllib.request.urlopen(url) as file:
        contents = file.read()
    match = re.compile(br'locales_with_principal_territory\s*\[\]\s*=\s*[{](.*?)[}]', re.DOTALL).search(contents)
    if match is None:
        raise ValueError
    contents = match.group(1)
    contents = re.compile(br'/[*].*?[*]/', re.DOTALL).sub(b'', contents)
    contents = contents.decode('ASCII')
    data = {}
    for item in re.findall('"(\w+)"', contents):
        language, gettext_cc = item.split('_')
        data[language] = gettext_cc
        try:
            our_cc = linginfo.get_principal_territory(language)
        except LookupError:
            continue
        if our_cc != gettext_cc:
            print('[{}]'.format(language))
            if our_cc is not None:
                print('# WAS: principal-territory =', our_cc)
            if linginfo.lookup_country_code(gettext_cc) is None:
                print('# BAD: principal-territory =', gettext_cc)
            else:
                print('principal-territory =', gettext_cc)
            print()
        else:
            okay.add(language)
    for language in linginfo.get_primary_languages():
        cc = linginfo.get_principal_territory(language)
        if cc is None:
            continue
        if language not in data:
            print('# WAS: [{}]'.format(language))
            print('# WAS: principal-territory =', cc)
            print()
    n_okay = len(okay)
    print('# No principal-territory changes required for {} languages'.format(n_okay))

if __name__ == '__main__':
    main()

# vim:ts=4 sw=4 et
