#!/bin/sh
version=${1:?"no version number provided"}
set -e -x
dch -m -v "$version" -u low -c doc/changelog
sed -i -E -e "s/(__version__) = '\S+'/\1 = '$version'/" lib/*.py
sed -i -E -e "s/^(:version: \S+) \S+$/\1 $version/" doc/*.txt
